name: Test

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  SRC_URL: https://downloads.wdc.com/gpl/WDMyCloud_Mirror_GPL_v5.18.117_20211022.tar.gz
  HOME_DIR: WDMyCloud_Mirror_GPL_v5.18.117_20211022
  OUTPUT_NAME: WDMyCloud_Mirror_GPL_v5.18.117_20211022
  DEVICE_NAME: WDMyCloud_Mirror
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "HOME_DIR=$GITHUB_WORKSPACE/$HOME_DIR" >> $GITHUB_ENV
        echo $HOME_DIR
        echo $OUTPUT_NAME-origin
        cp files/kernel/linux4.14.22/.config ./
        cp files/kernel/linux4.14.22/* ./
        patch -p1 < config-20220122.patch
        cat .config
        patch -p1 < xbuild-20220124.patch
        cat xbuild.sh
        cp -rf files/firmware/module/crfs ./
        cp files/firmware/module/iptables_install.patch
        patch -p1 < iptables_install.patch

    - name: Test1
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo $HOME_DIR