name: Test

on:
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 0 0 * * *

env:
  SRC_URL: https://downloads.wdc.com/gpl/WDMyCloud_Mirror_GPL_v5.18.117_20211022.tar.gz
  HOME_DIR: WDMyCloud_Mirror_GPL_v5.18.117_20211022
  OUTPUT_NAME: WDMyCloud_Mirror_GPL_v5.18.117_20211022
  DEVICE_NAME: WDMyCloud_Mirror
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq install dos2unix
        echo "HOME_DIR=$GITHUB_WORKSPACE/$HOME_DIR" >> $GITHUB_ENV
        echo $HOME_DIR
        echo $OUTPUT_NAME-origin
        cp files/kernel/linux4.14.22/.config ./
        cp files/kernel/linux4.14.22/* ./
        patch -p1 < config-20220122.patch
        patch -p1 < xbuild-20220124.patch
        cp -r files/firmware/module/ ./
        cd module
        patch -p1 < iptables_install-20220209.patch
        cat crfs/script/iptables_install.sh
        patch -p1 < lpd-conf-20220211.patch
        cat crfs/files/lpd.conf
        unix2dos define_js-20220212.patch
        patch --binary -p1 < define_js-20220212.patch
        cat crfs/web/pages_GT/function/define.js

    - name: Test1
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo $HOME_DIR