name: WDMyCloud_Mirror_GPL_v5.18 Image

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  SRC_URL: https://downloads.wdc.com/gpl/WDMyCloud_Mirror_GPL_v5.18.117_20211022.tar.gz
  HOME_DIR: WDMyCloud_Mirror_GPL_v5.18.117_20211022
  OUTPUT_NAME: WDMyCloud_Mirror_GPL_v5.18.117_20211022
  DEVICE_NAME: WDMyCloud_Mirror
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        chmod +x scripts/*
        sudo ./scripts/preset-build-env.sh
        echo "HOME_DIR=$GITHUB_WORKSPACE/$HOME_DIR" >> $GITHUB_ENV
        mkdir -p output/bin

    - name: Download Src
      run: |
        wget -q $SRC_URL
        tar -xzf *.tar.gz
        rm *.tar.gz

    - name: Extract the Linux kernel
      run: |
        cd $HOME_DIR/kernel
        tar zxvf linux-4.14.22.tar.gz
        cd linux-4.14.22
        chmod +x xbuild.sh

    - name: Build the Linux kernel
      run: |
        cd $HOME_DIR/kernel
        cd linux-4.14.22
        ./xbuild.sh build
        ls arch/arm/boot/uImage
        ls $HOME_DIR/firmware/merge/
        cp arch/arm/boot/uImage $HOME_DIR/firmware/merge/uImage
        cp arch/arm/boot/uImage $HOME_DIR/firmware/merge/uImage_origin
        cp arch/arm/boot/uImage $GITHUB_WORKSPACE/output/bin/uImage_origin
        cd ..
        ./build_ext_kernel_module.sh

    - name: Update kernel driver
      run: |
        cd $HOME_DIR/firmware/module
        cp -f $(find ../../kernel/linux-4.14.22/_install/lib/modules/4.14.22-armada-18.09.3/kernel/ -type f -name "*.ko") crfs/driver/

    - name: Include all non-open source binaries
      run: |
        cd $HOME_DIR/firmware/module
        ./mksquashfs.sh
        cp -f image.cfs ../merge/image_origin.cfs
        cp image.cfs $GITHUB_WORKSPACE/output/bin/image.cfs
        cp image.cfs $GITHUB_WORKSPACE/output/bin/image_origin.cfs

    - name: Build the root file system
      run: |
        cd $HOME_DIR/firmware/ramdisk
        sudo tar zxf rootfs.tar.gz
        sudo ./create_ramdisk.sh
        cp -f uRamdisk ../merge/
        cp uRamdisk $GITHUB_WORKSPACE/output/bin/uRamdisk

    - name: Build the origin firmware
      run: |
        cd $HOME_DIR/firmware/merge
        mv uImage uImage_patch
        cp uImage_origin uImage
        mv image.cfs image_origin.cfs
        cp image_origin.cfs image.cfs
        ./merge
        echo "::set-output name=status::success"
        cp WD-NAS-firmware $GITHUB_WORKSPACE/output/bin/$OUTPUT_NAME_origin.bin
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Patch the Linux kernel
      run: |
        cd $HOME_DIR/kernel/linux-4.14.22
        cp -f $GITHUB_WORKSPACE/files/kernel/linux4.14.22/config-20220122.patch .
        patch -p1 < config-20220122.patch

    - name: Build the patched Linux kernel
      run: |
        cd $HOME_DIR/kernel/linux-4.14.22
        ./xbuild.sh build
        cp arch/arm/boot/uImage $HOME_DIR/firmware/merge/uImage
        cp arch/arm/boot/uImage $GITHUB_WORKSPACE/output/bin/uImage
        cd ..
        ./build_ext_kernel_module.sh

    - name: Update patched kernel driver
      run: |
        cd $HOME_DIR/firmware/module
        #cp -f $(find ../../kernel/linux-4.14.22/_install/lib/modules/4.14.22-armada-18.09.3/kernel/ -type f -name "*.ko") crfs/driver/

    - name: Include all patched non-open source binaries
      run: |
        cd $HOME_DIR/firmware/module
        ./mksquashfs.sh
        cp -f image.cfs ../merge/
        cp image.cfs $GITHUB_WORKSPACE/output/bin/image.cfs
        cp image.cfs $GITHUB_WORKSPACE/output/bin/image.cfs

    - name: Build the patched firmware
      run: |
        cd $HOME_DIR/firmware/merge
        ./merge
        echo "::set-output name=status::success"
        cp WD-NAS-firmware $GITHUB_WORKSPACE/output/bin/$OUTPUT_NAME.bin
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: MyCloud_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: output/bin

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd output/bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        touch release.txt
        echo "WD My Cloud Mirror Fireware"
        echo "::set-output name=status::success"

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
